# Generated by Django 4.2.6 on 2023-10-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
                ('service', models.CharField(choices=[('Стоматология', 'Стоматология'), ('Косметология', 'Косметология')], max_length=100)),
                ('appointment_time', models.DateTimeField()),
            ],
        ),
    ]
