# Generated by Django 4.2.6 on 2023-10-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stomatolog', '0002_application_appointment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='appointment_date',
        ),
        migrations.AlterField(
            model_name='application',
            name='appointment_time',
            field=models.DateTimeField(),
        ),
    ]
