# Generated by Django 4.2.6 on 2023-10-16 02:19

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Stomatolog', '0004_alter_application_options_alter_application_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='appointment_time',
        ),
        migrations.AddField(
            model_name='application',
            name='appointment_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 16, 2, 17, 53, 726907, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
